### ISSUE TITLE
[HW] <Prateek Jain>

### ISSUE THREAD

**Issue by prateekengineer** [DataStax-Academy/Intro-to-Cassandra-for-Developers#14]
**Name:** <PRATEEK JAIN>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/5971611/110685716-9834a880-8204-11eb-8fc8-1a1093e540e7.png)

**Comment by HadesArchitect** [comment]
Closed as duplicate
