### ISSUE TITLE
[HW] Kapil Soni

### ISSUE THREAD

**Issue by kapilsoni-cse** [DataStax-Academy/Intro-to-Cassandra-for-Developers#145]
**Name:** Kapil Soni
**Email:** kapilsoni.cse@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/kapil-soni/

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

<img width="1440" alt="congrats_astra_crud" src="https://user-images.githubusercontent.com/22399614/120353576-658bdf00-c31f-11eb-83b1-8be668259d11.png">
<img width="1440" alt="congrats_data_models" src="https://user-images.githubusercontent.com/22399614/120353605-6ae92980-c31f-11eb-89e1-7b9e55a756f8.png">
<img width="1440" alt="cql_cassandra" src="https://user-images.githubusercontent.com/22399614/120353607-6b81c000-c31f-11eb-99f1-49256aa0e9e3.png">

**Comment by SonicDMG** [comment]
Looks great Kapil, thank you. Here's your badge -> https://api.badgr.io/public/assertions/kPGbjTQdQxyPKOBrtdYipg?identity__email=kapilsoni.cse%40gmail.com

**Comment by kapilsoni-cse** [comment]
Thank you! You guys are amazing...

**Comment by SonicDMG** [comment]
Oh wow, thank you for saying so Kapil. 😊
