### ISSUE TITLE
[HW] **Mark Smith**

### ISSUE THREAD

**Issue by Markhail1** [DataStax-Academy/Intro-to-Cassandra-for-Developers#154]
**Name:** <NAME>
**Email:** <email>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below for both step II and step III:
-----------------------------------------

<SCREENSHOT>

**Comment by SonicDMG** [comment]
Hey there Mark, I don't see anything attached. Could you please attach screenshots from steps 2 and 3 of the homework and provide your email address along with the name you want to use with your badge. Thank you.
https://github.com/DataStax-Academy/Intro-to-Cassandra-for-Developers#homework

**Comment by SonicDMG** [comment]
Actually, disregard, I found your other submission.
