### ISSUE TITLE
[HW] <Aayushi Chaudhari>

### ISSUE THREAD

**Issue by Jaiwin7** [DataStax-Academy/Intro-to-Cassandra-for-Developers#96]
**Name:** <Aayushi Chaudhari>
**Email:** <aayushichaudhari.ac06@gmail.com>
**Linkedin Profile:** <www.linkedin.com/in/aayushi-chaudhari-78212b106>

Attach the homework screenshots below for both step II and step III:
-----------------------------------------
[DataStax Homework.docx](https://github.com/DataStax-Academy/Intro-to-Cassandra-for-Developers/files/6472615/DataStax.Homework.docx)

**Comment by SonicDMG** [comment]
Thank you for your submission Aayushi. I see everything except for the screenshot from the "CRUD" step, step 3 in the repo. Please provide that screenshot.
