### ISSUE TITLE
[HW] <Aayushi Chaudhari>

### ISSUE THREAD

**Issue by aayushichaudhari** [DataStax-Academy/Intro-to-Cassandra-for-Developers#98]
**Name:** <Aayushi Chaudhari>
**Email:** <aayushichaudhari.ac06@gmail.com>
**Linkedin Profile:** <www.linkedin.com/in/aayushi-chaudhari-78212b106>

Here find the improvement needed in my homework.
Attach the homework screenshots below for both step II and step III:
-----------------------------------------

[Crud Document.docx](https://github.com/DataStax-Academy/Intro-to-Cassandra-for-Developers/files/6473354/Crud.Document.docx)

**Comment by SonicDMG** [comment]
Hi Aayushi, thank you for sending this over. The steps look good from the exercises in the repo. The only thing I am missing are the 2 scenarios from step 3 of the homework steps.
3. Complete the following short courses: [Cassandra Data Modeling](https://www.datastax.com/node/3272) and [Cassandra Query Language](https://www.datastax.com/dev/scenario/try-it-out-cassandra-query-language-cql). Take screenshots of the "Congratulations" page from each course.

Please provide those screenshots and we'll be good to go. :)

**Comment by SonicDMG** [comment]
Ok, between this and your other submission we are good. I have all of the materials. Thank you.

**Comment by HadesArchitect** [comment]
Duplicate #97
